// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvLCDcQRYhYMWk7uR26sjUfuwDUINaQU',
    appId: '1:704272791990:web:3534613e20b295278a6917',
    messagingSenderId: '704272791990',
    projectId: 'cross-platform-final-term',
    authDomain: 'cross-platform-final-term.firebaseapp.com',
    databaseURL: 'https://cross-platform-final-term-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cross-platform-final-term.appspot.com',
    measurementId: 'G-LS152KH0C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6o1LCQU7mFSuqBiUkDFddwG1nGW1dho',
    appId: '1:704272791990:android:4f0b5499fdf5215f8a6917',
    messagingSenderId: '704272791990',
    projectId: 'cross-platform-final-term',
    databaseURL: 'https://cross-platform-final-term-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cross-platform-final-term.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiclfYzapxJMW33Ofd-6QjYvIiqFNbAHw',
    appId: '1:704272791990:ios:a0a12bb1ac71bfd68a6917',
    messagingSenderId: '704272791990',
    projectId: 'cross-platform-final-term',
    databaseURL: 'https://cross-platform-final-term-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cross-platform-final-term.appspot.com',
    androidClientId: '704272791990-k7e19oaub26k812vem6jsvg89drsmnpv.apps.googleusercontent.com',
    iosClientId: '704272791990-30mrk1rekg9qfvp7qqn74jekcqjjeok1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiclfYzapxJMW33Ofd-6QjYvIiqFNbAHw',
    appId: '1:704272791990:ios:a0a12bb1ac71bfd68a6917',
    messagingSenderId: '704272791990',
    projectId: 'cross-platform-final-term',
    databaseURL: 'https://cross-platform-final-term-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cross-platform-final-term.appspot.com',
    androidClientId: '704272791990-k7e19oaub26k812vem6jsvg89drsmnpv.apps.googleusercontent.com',
    iosClientId: '704272791990-30mrk1rekg9qfvp7qqn74jekcqjjeok1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalterm',
  );

}